import type { PeriodExplanation } from "../lib/api";
import { formatMoney } from "../lib/format";
import { RecordChart } from "./chart";

export function ComparisonView({ account, currency, comparison }: Readonly<{ account?: string; currency?: string; comparison?: PeriodExplanation }>) {
  if (!account || !currency) return <section className="record-view"><p className="eyebrow">Compare</p><h1>What changed?</h1><p className="empty-note">Choose one account and one currency in the current scope to compare two periods.</p></section>;
  if (!comparison) return <section className="record-view"><p className="eyebrow">Compare</p><h1>What changed?</h1><p className="empty-note">There is no exact comparison available for this scope yet.</p></section>;
  return <section className="record-view" aria-labelledby="comparison-title"><p className="eyebrow">Compare</p><h1 id="comparison-title">What changed?</h1><p className="intro">{comparison.text}</p><dl className="comparison-totals"><div><dt>Earlier net</dt><dd>{formatMoney(comparison.before_net_amount_minor, currency)}</dd></div><div><dt>Later net</dt><dd>{formatMoney(comparison.after_net_amount_minor, currency)}</dd></div><div><dt>Exact change</dt><dd>{formatMoney(comparison.difference_net_amount_minor, currency)}</dd></div></dl><RecordChart title="Waterfall text alternative" values={comparison.contributions.map((contribution) => ({ label: contribution.label, value: formatMoney(contribution.amount_minor, currency) }))} /><table className="contribution-table"><caption>Exact contribution evidence</caption><thead><tr><th scope="col">Contributor</th><th scope="col">Change</th><th scope="col">Evidence rows</th></tr></thead><tbody>{comparison.contributions.map((contribution) => <tr key={contribution.label}><th scope="row">{contribution.label}</th><td>{formatMoney(contribution.amount_minor, currency)}</td><td>{contribution.before_transaction_ids.length + contribution.after_transaction_ids.length}</td></tr>)}</tbody></table></section>;
}
